# Generated by Django 4.2.1 on 2023-06-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='categoryId',
            new_name='category',
        ),
    ]
