# Generated by Django 4.2.1 on 2023-06-06 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0002_rename_categoryid_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
