# Generated by Django 4.2.1 on 2023-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exists',
            field=models.BooleanField(default=False),
        ),
    ]
